import React from 'react';

const Terms = () => {
    return (
        <div className="legal container slide-up">
            <h1 className="legal-title">Terms of Service</h1>
            <p className="legal-date">Last updated: April 2026</p>

            <section className="legal-section">
                <h2>Use of Service</h2>
                <p>Prompty provides a tool for generating AI prompts. By using this service, you agree to use it for lawful purposes and in accordance with these terms.</p>
            </section>

            <section className="legal-section">
                <h2>No Warranties</h2>
                <p>The prompts generated by Prompty are provided "as is". While we strive for high-fidelity outputs, we do not guarantee the accuracy, completeness, or usefulness of the generated content.</p>
            </section>

            <section className="legal-section">
                <h2>Limitation of Liability</h2>
                <p>Prompty shall not be liable for any damages arising out of the use or inability to use the service, including but not limited to AI-generated code errors or project delays.</p>
            </section>

            <style jsx="true">{`
        .legal {
          padding-top: var(--spacing-xl);
          max-width: 800px;
          padding-bottom: var(--spacing-xl);
        }
        .legal-title {
          font-size: 3.5rem;
          margin-bottom: 0.5rem;
        }
        .legal-date {
          color: var(--gray-medium);
          margin-bottom: var(--spacing-xl);
        }
        .legal-section {
          margin-bottom: var(--spacing-lg);
        }
        .legal-section h2 {
          font-size: 1.5rem;
          margin-bottom: 1rem;
        }
        .legal-section p {
          line-height: 1.6;
          color: var(--gray-medium);
        }
      `}</style>
        </div>
    );
};

export default Terms;
